export const ALL_TOUR_SUCCESS = "ALL_TOUR_SUCCESS"
export const ALL_TOUR_REQUEST = "ALL_TOUR_REQUEST"
export const ALL_TOUR_FAIL = "ALL_TOUR_FAIL"

export const TOUR_DETAIL_SUCCESS = "TOUR_DETAIL_SUCCESS"
export const TOUR_DETAIL_REQUEST = "TOUR_DETAIL_REQUEST"
export const TOUR_DETAIL_FAIL = "TOUR_DETAIL__FAIL"

export const ERROR_CLEAR = "ERROR_CLEAR"