export const USER_REQUIEST = "USER_REQUIEST"
export const USER_SUCCESS = "USER_SUCCESS"
export const USER_FAIL = "USER_FAIL"

export const USER_REGISTER_REQUIEST = "USER_REGISTER_REQUIEST"
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS"
export const USER_REGISTER_FAIL = "UREGISTER_SER_FAIL"

export const LOAD_USER_REQUIEST = "USER_REGISTER_REQUIEST"
export const LOAD_USER_SUCCESS = "USER_REGISTER_SUCCESS"
export const LOAD_USER_FAIL = "UREGISTER_SER_FAIL"

export const USER_LOGOUT_REQUIEST = "USER_LOGOUT_REQUIEST"
export const USER_LOGOUT_SUCCESS = "USER_LOGOUT_SUCCESS"
export const USER_LOGOUT_FAIL = "USER_LOGOUT_FAIL"

export const USER_ERROR = "USER_ERROR"