# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI/CD

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v3

    - name: Set ownership and permissions
      run: |
        sudo chown -R $(whoami):$(whoami) .
        chmod -R u+rwX .

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Cleanup node_modules
      run: sudo rm -rf ./node_modules

    - name: Install dependencies
      run: npm ci

    - name: Setup Environment File
      run: |
        touch config.env
        echo "${{ secrets.PROD_ENV_FILE }}" > config.env

    - name: Restart application with PM2
      run: pm2 restart tourbooking
    - run: pm2 restart tourbooking
